### ISSUE TITLE
kl_loss reaches 1e6, and samples generated are completely noise 

### ISSUE THREAD

**Issue by ZhaoxinShi-beep** [SerezD/NVAE-from-scratch#3]
Hi there! Sorry to bother you, I have found your code extremely useful, but when I checked the tensorboard logs, I found that the reconstuction result is fine, while the kl_loss reached as much as 1e6. And the sampled results are completely noise images. The bach size is 10, and I used 5 A6000 with a learning rate of 1e-3. I wonder if this is usual or something is wrong.
![image](https://github.com/user-attachments/assets/0fd1d7a6-b9fe-4e22-b122-8e09b13f9bcd)
![image](https://github.com/user-attachments/assets/71b279df-1bca-44fb-9f00-e7115c43fdf0)

**Comment by SerezD** [comment]
Hi there, 

My first guess is that your problem may be due to a wrong hyperparameter selection. What values are you using for spectral regularization (weight decay) and KL annealing? 
These are important parameters to prevent KL from exploding, which is the main issue in training NVAE. 
Also, for a batch size of 10, I think the LR is a bit high. 

As an example, my celeb-a model uses the following configuration: 
```
resolution:
  - 3
  - 64
  - 64

autoencoder:
  num_scales: 3 # the number of downsamples in encoder tower (latent scales)
  num_groups_per_scale: 8 # number of groups (latent variables) per scale
  is_adaptive: false # Settings this to true will set different number of groups per scale (starting by num groups per scale and div by 2, up to min groups_per_scale)
  min_groups_per_scale: 1 # the minimum number of groups per scale.
  num_cells_per_group: 2 # number of cell for each conditional in encoder
  num_latent_per_group: 16 # number of channels in group latent variables
  num_nf_cells:  # guess that nf cells are useful especially in the first scales (high dependency between GLOBAL variables)
  initial_channels: 128 # number of initial channels in encoder
  num_pre-post_process_blocks: 1 # number of pre/post processing blocks (each one down/up scales image)
  num_pre-post_process_cells: 2 # number of cells per pre/post processing block
  num_logistic_mixtures: 10 # num of logistic

training:
  seed: 0
  epochs: 600
  warmup_epochs: 5
  cumulative_bs: 256
  base_lr: 1e-3 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  min_lr: 5e-4 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  weight_decay: 3e-4
  eps: 1e-3
  spectral_regularization:
    weight_decay_norm: 0.1  # The lambda parameter for spectral regularization.
    weight_decay_norm_anneal: False  # anneal lambda
    weight_decay_norm_init: 10.  # The initial lambda parameter (only used if anneal)
  kl_anneal:
    kl_anneal_portion: 0.3 # perc of total epochs that KL is annealed
    kl_const_portion: 0.0001 # perc of total epochs that KL is constant at kl_const_coeff
    kl_const_coeff: 0.0001 # The constant value used for min KL coeff
```

My training plots look like: 
![image](https://github.com/user-attachments/assets/6d812d80-8300-46f8-9108-f31221ac3e4b)

My Validation plot look like: 
![image](https://github.com/user-attachments/assets/0e62f4e8-79d9-4855-9375-51d490b79306)

And Sampled images are "meaningful" after 2000 steps: 
![image](https://github.com/user-attachments/assets/a1a5d915-94cf-4783-b53d-b2e5bda267d1)

**Comment by 37integer** [comment]
hi, i also have kind similar problem
this is the result i use celeb256 dataset to train, for the config i use:
`resolution:
  - 3
  - 256
  - 256

autoencoder:
  num_scales: 5 # the number of downsamples in encoder tower (latent scales)
  num_groups_per_scale: 16 # number of groups (latent variables) per scale
  is_adaptive: true # Settings this to true will set different number of groups per scale (starting by num groups per scale and div by 2, up to min groups_per_scale)
  min_groups_per_scale: 4 # the minimum number of groups per scale (relevant only if is_adaptive).
  num_cells_per_group: 2 # number of cells for each group in encoder
  num_latent_per_group: 20 # number of channels in each latent variable
  num_nf_cells:  # (optional) number of NF cells used in Encoder to ensure global dependency of latent variables.
  initial_channels: 32 # number of initial channels in encoder
  num_pre-post_process_blocks: 1 # number of pre/post processing blocks (each one down/up scales image)
  num_pre-post_process_cells: 2 # number of cells per pre/post processing block
  num_logistic_mixtures: 10 # num of logistic for the final Decoding from logits to RGB images

training:
  seed: 0
  epochs: 1000
  warmup_epochs: 5
  cumulative_bs: 8
  base_lr: 1e-2 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  min_lr: 1e-4 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  weight_decay: 3e-4
  eps: 1e-3
  spectral_regularization:
    weight_decay_norm: 1e-2  # The lambda parameter for spectral regularization.
    weight_decay_norm_anneal: False  # anneal lambda
    weight_decay_norm_init: 10.  # The initial lambda parameter (only used if anneal)
  kl_anneal:
    kl_anneal_portion: 0.3 # perc of total epochs that KL is annealed
    kl_const_portion: 0.0001 # perc of total epochs that KL is constant at kl_const_coeff
    kl_const_coeff: 0.0001 # The constant value used for min KL coeff
`
you can see the result is so weird, and kl loss also.
<img width="886" alt="スクリーンショット 2024-11-15 014600" src="https://github.com/user-attachments/assets/de8966cb-9a67-4580-a4a5-2eadcf26ef29">
<img width="295" alt="2" src="https://github.com/user-attachments/assets/299b60c0-a655-4e4b-be48-52b02d969081">

also i have try to train mnist dataset by using your base_config, the result is also weird:
<img width="288" alt="3" src="https://github.com/user-attachments/assets/be8e0a5b-2a9d-4581-bf94-c600895df47a">
<img width="891" alt="4" src="https://github.com/user-attachments/assets/ad69a16f-6a3b-4f79-a9db-c46a3519bfd0">

do you have any idea of this problem?

**Comment by ZhaoxinShi-beep** [comment]
> Hi there,
> 
> My first guess is that your problem may be due to a wrong hyperparameter selection. What values are you using for spectral regularization (weight decay) and KL annealing? These are important parameters to prevent KL from exploding, which is the main issue in training NVAE. Also, for a batch size of 10, I think the LR is a bit high.
> 
> As an example, my celeb-a model uses the following configuration:
> 
> ```
> resolution:
>   - 3
>   - 64
>   - 64
> 
> autoencoder:
>   num_scales: 3 # the number of downsamples in encoder tower (latent scales)
>   num_groups_per_scale: 8 # number of groups (latent variables) per scale
>   is_adaptive: false # Settings this to true will set different number of groups per scale (starting by num groups per scale and div by 2, up to min groups_per_scale)
>   min_groups_per_scale: 1 # the minimum number of groups per scale.
>   num_cells_per_group: 2 # number of cell for each conditional in encoder
>   num_latent_per_group: 16 # number of channels in group latent variables
>   num_nf_cells:  # guess that nf cells are useful especially in the first scales (high dependency between GLOBAL variables)
>   initial_channels: 128 # number of initial channels in encoder
>   num_pre-post_process_blocks: 1 # number of pre/post processing blocks (each one down/up scales image)
>   num_pre-post_process_cells: 2 # number of cells per pre/post processing block
>   num_logistic_mixtures: 10 # num of logistic
> 
> training:
>   seed: 0
>   epochs: 600
>   warmup_epochs: 5
>   cumulative_bs: 256
>   base_lr: 1e-3 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
>   min_lr: 5e-4 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
>   weight_decay: 3e-4
>   eps: 1e-3
>   spectral_regularization:
>     weight_decay_norm: 0.1  # The lambda parameter for spectral regularization.
>     weight_decay_norm_anneal: False  # anneal lambda
>     weight_decay_norm_init: 10.  # The initial lambda parameter (only used if anneal)
>   kl_anneal:
>     kl_anneal_portion: 0.3 # perc of total epochs that KL is annealed
>     kl_const_portion: 0.0001 # perc of total epochs that KL is constant at kl_const_coeff
>     kl_const_coeff: 0.0001 # The constant value used for min KL coeff
> ```
> 
> My training plots look like: ![image](https://private-user-images.githubusercontent.com/68145713/386115401-6d812d80-8300-46f8-9108-f31221ac3e4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzIxMDcsIm5iZiI6MTczMTYzMTgwNywicGF0aCI6Ii82ODE0NTcxMy8zODYxMTU0MDEtNmQ4MTJkODAtODMwMC00NmY4LTkxMDgtZjMxMjIxYWMzZTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAwNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNGZmYTljOTYxYzhlYzI5NWQ3OWRkZDMwZmJjODU3YTYxYTcyNjlkZmE2N2MyYzEyOWJmNTRkYjU1Y2YyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ssP6fpp2NQ5d4n5zh_Q4Y2-zvgMHI9GpPvdNjLJbfok)
> 
> My Validation plot look like: ![image](https://private-user-images.githubusercontent.com/68145713/386115663-0e62f4e8-79d9-4855-9375-51d490b79306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzIxMDcsIm5iZiI6MTczMTYzMTgwNywicGF0aCI6Ii82ODE0NTcxMy8zODYxMTU2NjMtMGU2MmY0ZTgtNzlkOS00ODU1LTkzNzUtNTFkNDkwYjc5MzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAwNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOWMzNDZlM2U2NmI5MmY1ZThhMGNiZjI4MmNhNmZkN2EwYTI3MDU2NjQ4M2E5MmU4N2FkZWJjYzYzODRmYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MG5H8Au2K62UEb19pVhf_bXli97VmbIPP8ZT0C0dVWs)
> 
> And Sampled images are "meaningful" after 2000 steps: ![image](https://private-user-images.githubusercontent.com/68145713/386116273-a1a5d915-94cf-4783-b53d-b2e5bda267d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzIxMDcsIm5iZiI6MTczMTYzMTgwNywicGF0aCI6Ii82ODE0NTcxMy8zODYxMTYyNzMtYTFhNWQ5MTUtOTRjZi00NzgzLWI1M2QtYjJlNWJkYTI2N2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAwNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjExNGMzM2RjMmZhZDUyYWYyOWMxYTNjNzFlNmQzYTBiNzE1OTVkYzg1NjMwNWI0NmRhMmZhZjllMzE5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RcAvIYNdB80cUjIhCYyp4PJoTPm2B68WDJsqAUxVtFU)

Thanks for your pointer, I'll try to find out what the appropriate hyperparameters are for my setting. Below is my original settings, I didn't change anything except the resolution and cumulative_bs.


resolution:
  - 3
  - 128
  - 128

autoencoder:
  num_scales: 3 # the number of downsamples in encoder tower (latent scales)
  num_groups_per_scale: 8 # number of groups (latent variables) per scale
  is_adaptive: false # Settings this to true will set different number of groups per scale (starting by num groups per scale and div by 2, up to min groups_per_scale)
  min_groups_per_scale: 1 # the minimum number of groups per scale (relevant only if is_adaptive).
  num_cells_per_group: 2 # number of cells for each group in encoder
  num_latent_per_group: 20 # number of channels in each latent variable
  num_nf_cells:  # (optional) number of NF cells used in Encoder to ensure global dependency of latent variables.
  initial_channels: 128 # number of initial channels in encoder
  num_pre-post_process_blocks: 1 # number of pre/post processing blocks (each one down/up scales image)
  num_pre-post_process_cells: 2 # number of cells per pre/post processing block
  num_logistic_mixtures: 10 # num of logistic for the final Decoding from logits to RGB images

training:
  seed: 1234
  epochs: 400
  warmup_epochs: 5
  cumulative_bs: 8
  base_lr: 1e-2 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  min_lr: 1e-4 # refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced
  weight_decay: 3e-4
  eps: 1e-3
  spectral_regularization:
    weight_decay_norm: 1e-2  # The lambda parameter for spectral regularization.
    weight_decay_norm_anneal: False  # anneal lambda
    weight_decay_norm_init: 10.  # The initial lambda parameter (only used if anneal)
  kl_anneal:
    kl_anneal_portion: 0.3 # perc of total epochs that KL is annealed
    kl_const_portion: 0.0001 # perc of total epochs that KL is constant at kl_const_coeff
    kl_const_coeff: 0.0001 # The constant value used for min KL coeff
  output_log_folder: 'output_logs2'

**Comment by SerezD** [comment]
Hi all, 

Here are some general considerations, mostly based on my experience attempting to train NVAE. Please consider that some parts may be wrong/don't apply to your specific configurations.

**Training on Celeb-A 128 or 256**

In the original repo: https://github.com/NVlabs/NVAE?tab=readme-ov-file they state for the configuration CELEBA-256:   
*24 32-GB V100 GPUs are used for training NVAE on CelebA HQ 256. Training takes about 94 hours.
In our early experiments, a smaller model with 24 channels instead of 30, could be trained on only 8 GPUs in the same time (with a batch size of 6).*

Their configuration is something like: 

```
resolution:
  - 3
  - 256
  - 256

autoencoder:
  num_scales: 5 
  num_groups_per_scale: 16 
  is_adaptive: true
  min_groups_per_scale: 4 
  num_cells_per_group: 2 
  num_latent_per_group: 20
  num_nf_cells: 2
  initial_channels: 30 or 24
  num_pre-post_process_blocks: 1 
  num_pre-post_process_cells: 2
  num_logistic_mixtures: 10 

training:
  seed: 0
  epochs: 300
  warmup_epochs: 5
  cumulative_bs: 4 * 24 or 6 * 8
  base_lr: 1e-2
  min_lr: 1e-4
  weight_decay: 3e-4
  eps: 1e-3
  spectral_regularization:
    weight_decay_norm: 1e-2
    weight_decay_norm_anneal: True
    weight_decay_norm_init: 1.
  kl_anneal:
    kl_anneal_portion: 0.3 
    kl_const_portion: 0.0001 
    kl_const_coeff: 0.0001
```

So my first suggestion is to start from a config like theirs, and adapt it as needed. For example, in a 128-resolution setup, I would reduce the number of scales to 4.
The other main problem concerns the batch size, which in your case is only 8. In that case, I would reduce the learning rate to at least 1e-3 or even less. Usually, smaller batch sizes imply lower learning rates, as described for example here: https://www.baeldung.com/cs/learning-rate-batch-size

I know that in my config file it is written: "# refers to LR for cumulative_bs = 512. Will scale automatically if bs is increased/reduced". That is not true in the current version of the repo, sorry for that. In any case, the batch size you specify is the cumulative batch size that will be used.

Also, a smaller batch size will largely increase the total training time, so training will last much longer than the 94 ours they state.

**Posterior Collapse**
Another common problem is posterior collapse. Since many latent variables are used, the model will attempt to "simplify" training by turning off one or more latent variables (all of them in pathological cases). To prevent this, they force balancing of the KL terms in the first 30% of training, also slowly increasing the beta terms from 0 to 1. One thing you may try is to increase the `kl_anneal_portion: 0.3`, and observe if this helps.   

Also, another thing you may try is to reduce the number of groups per scale. This would also reduce the total model size, maybe allowing to increase the batch size. While a large number of groups allow obtaining more expressive distributions, I often noted that increasing the value too much simply adds complexity to training, without many benefits. 

**Spectral Regularization**
As indicated in Section A of the supplementary material of the NVAE paper, the Lambda parameter is very important in stabilizing training. They use fixed values of 1e-2 or 1e-1 for smaller models, or even higher values for CelebA and FFHQ. In this case, Lambda starts e.g. at 1 or 10 and is then annealed during training, as indicated in the corresponding configuration parameters above. In my configuration on Celeba 64 I used a fixed lambda value of 0.1, but for higher resolution starting with higher lambda values is probably crucial.

**MINST Dataset**
I have never tried to train on MINST, so I have no idea of what a correct configuration should look like. In general, all things mentioned above play a crucial role and should be adapted to each specific case. 

In general, reconstruction loss should smoothly decrease, while KL loss should smoothly increase during learning. high drops or peaks of loss values usually denote a poor configuration (or a bug in the implementation, which of course may always be). 

I hope these comments will be helpful. Good luck with your training!
